[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lending_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgAGF4d8CLQN"

[programs.testnet]
lending_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgAGF4d8CLQN"

[programs.mainnet]
lending_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgAGF4d8CLQN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metaplex_token_metadata.so"

[test.validator]
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
bind_address = "0.0.0.0"
rpc_port = 8899
websocket_port = 8900
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[build]
exclude = ["node_modules"]
